name: Java CI with Gradle

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build and test with Gradle
      run: ./gradlew build jacocoTestReport

    - name: Check test coverage
      run: ./gradlew jacocoTestReport

    - name: Check that all tests pass
      run: ./gradlew check --stacktrace

    - name: Upload Code Coverage
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: build/reports/jacoco/test/html


