name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_URL_TEST: ${{ secrets.DB_URL_TEST }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew build -PDB_URL=$DB_URL_TEST
